### ISSUE TITLE
Test target variable against all others

### ISSUE THREAD

**Issue by GGG-del** [8080labs/ppscore#13]
Hello!

I wonder if there is a possibility to test a single target variable against all others and further print the coefficient in descending order?

pps.score(df, "x", "y")

What do I put instead of "x" in that case? 
Sorry, Im rather new to Python.

**Comment by 8080labs** [comment]
Hi,

I guess what you want is a separate `pps.predictors(df, y)` function which just returns what you ask for.
We plan to provide such a function in the future.

In the meantime you can try the following code:
```python
import ppscore as pps

scores = [pps.score(df, str(column), "y") for column in df.columns]

scores.sort(key=lambda item: item["ppscore"], reverse=True)

for score in scores:
    print(f"{score['ppscore']:.2f} using {score['x']}")
```

I hope this helps,
Florian

**Comment by GGG-del** [comment]
Hi Florian,

Thank you for the prompt reply and for addressing my issue. It worked just the way I expected. Thank you for your work and good luck with it.

**Comment by 8080labs** [comment]
You're welcome!
