### ISSUE TITLE
How to understand the baseline_score?

### ISSUE THREAD

**Issue by NicholaiStaalung** [8080labs/ppscore#18]
Hi,

Im having trouble understanding the baseline score. From what i think i can see in the code then the baseline is the score when we are being naive and choosing the median of y as our predicted value.

That would mean if the baseline_score is higher than the model_score then using the median as a the predicited value would be better than the prediction from the decision tree. Is this correct?

Btw. Thanks for releasing

**Comment by 8080labs** [comment]
Hi Nicholai,

your understanding is correct :)

Florian

**Comment by NicholaiStaalung** [comment]
Thanks!
