### ISSUE TITLE
Failure to handle dtype=category

### ISSUE THREAD

**Issue by realauggieheschmeyer** [8080labs/ppscore#24]
I am having a similar issue to #11. I recreated the sample dataset from their example but with 100 rows and made features 2 and 3 both categorical. When I run `pps.matrix` with features 2 and 3 as `dtype=object`, I get the expected outcome. However, if I convert those same features to `dtype=category`, the output of `pps.matrix` for those features are only 1's and 0's. Is this intentional behavior? I appreciate your help. Thank you.

This works: 
```
#importing the libs
import ppscore as pps
import numpy as np
import pandas as pd

#Creating a sample df
col1 = np.random.randn(100)*10
col2 = np.random.choice(['cat1', 'cat2', 'cat3', 'cat4'],100)
col3 = np.random.choice(['yes', 'no'],100)

#creating dataframe
df=pd.DataFrame(
{'feature1': col1,
'feature2': col2,
'feature3':col3}
)

#trying to calculate pps matrix
pps.matrix(df)
```

This does not:
```
df['feature2'] = pd.Categorical(df.feature2)
df['feature3'] = pd.Categorical(df.feature3)

pps.matrix(df)
```

**Comment by FlorianWetschoreck** [comment]
Hi Auggie, thank you for reporting this issue. Indeed, there is a bug if the column has the dtype Categorical. We will have a look into it and fix it. In the meantime, please convert categorical variables to strings with dtype object

**Comment by FlorianWetschoreck** [comment]
Also, we found out that the naive baseline of always predicting the most common class underperforms a random guess if the categories are uniformely distributed - like in your case. We will also fix this

**Comment by realauggieheschmeyer** [comment]
Thanks for the update, @FlorianWetschoreck. My actual dataset didn't have many variables so implementing your solution required relatively little effort. I look forward to continuing the package more in the future. It's terrific. My Product Manager has already commented on how useful it's going to be.
