### ISSUE TITLE
Requirements not installed when using pip

### ISSUE THREAD

**Issue by neffmallon** [8080labs/ppscore#29]
Currently, setup.py doesn't include the package dependencies, so they don't automatically install when using `pip install`.

To fix this, use the `install_requires` kwarg in the `setup()` call in setup.py. Documentation and examples are available here: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies

**Comment by FlorianWetschoreck** [comment]
Thank you for pointing this out, Nathan
We will have a look at it and fix it

**Comment by tkrabel** [comment]
Should be fixed now with release 1.1.1
