### ISSUE TITLE
PPS not working for my dataset( Financial Data)

### ISSUE THREAD

**Issue by RohanTrix** [8080labs/ppscore#30]
### The following is the output for PPS
![image](https://user-images.githubusercontent.com/52482556/89068228-76319880-d38e-11ea-9292-b842f7ad1b68.png)
### The following is the output for Correlation
![image](https://user-images.githubusercontent.com/52482556/89068370-b4c75300-d38e-11ea-8bca-e4213be76692.png)

**Correlation works perfectly okay but the PPS is giving me weird results**
The dataset link is:
[dataset6 TO 10.xlsx](https://github.com/8080labs/ppscore/files/5008621/dataset6.TO.10.xlsx)

Please help me resolve this, I am trying to predict Ev/EBITDA here.

**Comment by FlorianWetschoreck** [comment]
It seems like this issue is related to your specific data.
I reached out to you on Linkedin so that we can continue the discussion.

**Comment by FlorianWetschoreck** [comment]
Closed due to inactivity
