### ISSUE TITLE
pps.score not executing

### ISSUE THREAD

**Issue by apavlo89** [8080labs/ppscore#31]
Hello,

I can get pps.matrix to work just fine but I'm having trouble running pps.score.

I get "TypeError: unhashable type: 'numpy.ndarray'"

This is the code I've used

```
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import ppscore as pps

dataset = pd.read_csv('D:/location/test.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

pps_matrix_results = pps.matrix(dataset)
pps_score_results = pps.score(dataset, x,y)

```

What am I doing wrong?

**Comment by tkrabel** [comment]
Hi @apavlo89 

Among others, `pps.score` has the following arguments:

```
Parameters
    ----------
    df : pandas.DataFrame
        Dataframe that contains the columns x and y
    x : str
        Name of the column x which acts as the feature
    y : str
        Name of the column y which acts as the target
```

As you can see, there are two things you need to consider:

1. `x` and `y` need to be column names of `dataset`, so passing numpy arrays is not supported
2. you can only pass one column (name) for both `x`and `y`.

Does that help?

**Comment by apavlo89** [comment]
Yes, it totally makes sense now. Thank you for your help!
