### ISSUE TITLE
pps.matrix and pps.predictors are giving different score values for the same dataset against the same target feature

### ISSUE THREAD

**Issue by madhavi1102** [8080labs/ppscore#32]
Hi All,

Found useful for extracting non linear relations . What I understood that the relation estimated by ppscore between the two variables or features are not impacted by the other available variables if I use pps.matrix ,or pps.predictors().  Does my understanding correct? 

Found weird that pps.matrix tends to give different scores for features  that pps.predictors() for the same target column .
Can you check what is the cause for the difference, is it valid ?

**Comment by FlorianWetschoreck** [comment]
Hi Maddy,

thank you for pointing this out. The reason for this is that there are some parts of the PPS which are not deterministic but instead rely on random samples.
Currently, the default for sampling is that a new random_seed is drawn for each calculation and thus you do not see consistent results.
We had an internal discussion and think that we prefer to set the random_seed per default.
So, in the next version of PPS the results will be the same.

Best,
Florian
