### ISSUE TITLE
[SUGGEST] Release a verson supported GPU

### ISSUE THREAD

**Issue by mainguyenanhvu** [8080labs/ppscore#49]
Thank you for creating a power metric to calculate the score for choosing features.

I hope that you can release a version which supports to calculate this score by GPU. It will reduce time for computating. 

Thank you.

**Comment by FlorianWetschoreck** [comment]
Hi, thank you for reaching out. On what kind of data sizes are you executing the pps? Do you have time yourself to provide this PR or does the organization you work for have funds for this?

**Comment by mainguyenanhvu** [comment]
I made a pull request for this suggestion. Thank you.
